2020-08-12 10:58:59,960 | pipeline_preparation | INFO: NER pipeline added
2020-08-12 10:58:59,961 | pipeline_preparation | INFO: Pattern matching pipeline added
2020-08-12 10:59:31,105 | pipeline_preparation | INFO: NER pipeline added
2020-08-12 10:59:31,105 | pipeline_preparation | INFO: Pattern matching pipeline added
2020-08-12 11:00:17,261 | pipeline_preparation | INFO: NER pipeline added
2020-08-12 11:00:17,261 | pipeline_preparation | INFO: Pattern matching pipeline added
2020-08-12 11:00:21,752 | pipeline_preparation | INFO: NER pipeline added
2020-08-12 11:00:21,752 | pipeline_preparation | INFO: Pattern matching pipeline added
2020-08-12 11:16:46,474 | pipeline_preparation | INFO: NER pipeline added
2020-08-12 11:16:46,474 | pipeline_preparation | INFO: Pattern matching pipeline added
2020-08-12 13:02:15,519 | pipeline_preparation | ERROR: 'Predefined_soft_skills'
Traceback (most recent call last):
  File "C:\Users\Aakash\Desktop\Python\Scraping\Projects\dolp_env\lib\site-packages\pandas\core\indexes\base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas\_libs\index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Predefined_soft_skills'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Aakash\Desktop\Python\Scraping\Projects\dolphin2\seven\dolphin\cvparser\pipeline.py", line 43, in __init__
    predefined_soft_skills = pd.read_csv(cfg.soft_skills_pool)['Predefined_soft_skills'].to_list()
  File "C:\Users\Aakash\Desktop\Python\Scraping\Projects\dolp_env\lib\site-packages\pandas\core\frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\Aakash\Desktop\Python\Scraping\Projects\dolp_env\lib\site-packages\pandas\core\indexes\base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas\_libs\index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Predefined_soft_skills'
2020-08-12 13:05:26,033 | pipeline_preparation | INFO: NER pipeline added
2020-08-12 13:05:26,033 | pipeline_preparation | INFO: Pattern matching pipeline added
2020-08-12 13:06:02,807 | pipeline_preparation | INFO: NER pipeline added
2020-08-12 13:06:02,807 | pipeline_preparation | INFO: Pattern matching pipeline added
2020-08-12 18:23:01,508 | pipeline_preparation | INFO: NER pipeline added
2020-08-12 18:23:01,508 | pipeline_preparation | INFO: Pattern matching pipeline added
2020-08-12 18:23:05,552 | pipeline_preparation | INFO: NER pipeline added
2020-08-12 18:23:05,552 | pipeline_preparation | INFO: Pattern matching pipeline added
2020-08-12 18:24:14,736 | pipeline_preparation | INFO: NER pipeline added
2020-08-12 18:24:14,737 | pipeline_preparation | INFO: Pattern matching pipeline added
2020-08-12 18:24:18,307 | pipeline_preparation | INFO: NER pipeline added
2020-08-12 18:24:18,307 | pipeline_preparation | INFO: Pattern matching pipeline added
2020-08-12 18:29:59,451 | pipeline_preparation | INFO: NER pipeline added
2020-08-12 18:29:59,451 | pipeline_preparation | INFO: Pattern matching pipeline added
2020-08-12 18:30:06,911 | pipeline_preparation | INFO: NER pipeline added
2020-08-12 18:30:06,911 | pipeline_preparation | INFO: Pattern matching pipeline added
